<?php

namespace Common\RegionBundle\Repository;

/**
 * RegionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RegionRepository extends \Doctrine\ORM\EntityRepository
{
    public function getBuilder()
    {
        return $this->createQueryBuilder("r");
    }
}
