<?php

namespace Team\TeamBundle\Repository;

/**
 * TeamRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TeamRepository extends \Doctrine\ORM\EntityRepository
{
    public function updateTeamGoalIn($team,$goals)
    {
        $qb = $this->em->createQueryBuilder();
        $q = $qb->update('Team', 't')
            ->set('t.goalsIn', 't.goalsIn + ?1')
            ->where('t.id = ?2')
            ->setParameter(1, $goals)
            ->setParameter(2, $team)
            ->getQuery();
        $q->execute();
    }
    public function updateTeamGoalScored($team,$goals)
    {
        $qb = $this->em->createQueryBuilder();
        $q = $qb->update('Team', 't')
            ->set('t.goalsScored', 't.goalsScored + ?1')
            ->where('t.id = ?2')
            ->setParameter(1, $goals)
            ->setParameter(2, $team)
            ->getQuery();
        $q->execute();
    }
}
