player:
    resource: "@PlayerBundle/Controller/"
    type:     annotation
    prefix:   /

team:
    resource: "@TeamBundle/Controller/"
    type:     annotation
    prefix:   /

forum:
    resource: "@ForumBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type:     annotation

front:
    resource: "@FrontBundle/Controller/"
    type:     annotation
    prefix:   /front

back:
    resource: "@BackBundle/Controller/"
    type:     annotation
    prefix:   /admin

user:
    resource: "@UserBundle/Controller/"
    type:     annotation
    prefix:   /

user_yml:
    resource: "@UserBundle/Resources/config/routing.yml"
