cart:
    resource: "@CartBundle/Controller/"
    type:     annotation
    prefix:   /

match:
    resource: "@MatchBundle/Controller/"
    type:     annotation
    prefix:   /

booking:
    resource: "@BookingBundle/Controller/"
    type:     annotation
    prefix:   /

upload:
    resource: "@UploadBundle/Resources/config/routing.yml"
    prefix:   /

location_location:
    resource: "@LocationBundle/Controller/LocationController.php"
    type:     annotation

location_address:
    resource: "@LocationBundle/Controller/AddressController.php"
    type:     annotation

region_region:
    resource: "@RegionBundle/Controller/RegionController.php"
    type:     annotation

hotel_room:
    resource: "@HotelBundle/Controller/RoomController.php"
    type:     annotation

hotel_hotel:
    resource: "@HotelBundle/Controller/HotelController.php"
    type:     annotation

region:
    resource: "@RegionBundle/Controller/"
    type:     annotation
    prefix:   /

location:
    resource: "@LocationBundle/Controller/"
    type:     annotation
    prefix:   /

guide:
    resource: "@GuideBundle/Controller/"
    type:     annotation
    prefix:   /

ticket:
    resource: "@TicketBundle/Controller/"
    type:     annotation
    prefix:   /

hotel:
    resource: "@HotelBundle/Controller/"
    type:     annotation
    prefix:   /

group:
    resource: "@GroupBundle/Controller/"
    type:     annotation
    prefix:   /

player:
    resource: "@PlayerBundle/Controller/"
    type:     annotation
    prefix:   /

team:
    resource: "@TeamBundle/Controller/"
    type:     annotation
    prefix:   /

forum:
    resource: "@ForumBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type:     annotation

front:
    resource: "@FrontBundle/Controller/"
    type:     annotation
    prefix:   /

back:
    resource: "@BackBundle/Controller/"
    type:     annotation
    prefix:   /admin

user:
    resource: "@UserBundle/Controller/"
    type:     annotation
    prefix:   /

user_yml:
    resource: "@UserBundle/Resources/config/routing.yml"

fos_js_routing:
  resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"