team_front:
    resource: "@TeamFrontBundle/Controller/"
    type:     annotation
    prefix:   /team

team_back:
    resource: "@TeamBackBundle/Controller/"
    type:     annotation
    prefix:   /

player_front:
    resource: "@PlayerFrontBundle/Controller/"
    type:     annotation
    prefix:   /player

player_back:
    resource: "@PlayerBackBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type:     annotation

front:
    resource: "@FrontBundle/Controller/"
    type:     annotation
    prefix:   /front

back:
    resource: "@BackBundle/Controller/"
    type:     annotation
    prefix:   /admin