team:
    resource: "@TeamBundle/Resources/config/routing.yml"
    prefix:   /Team

joueur:
    resource: "@JoueurBundle/Resources/config/routing.yml"
    prefix:   /Joueur

app:
    resource: '@AppBundle/Controller/'
    type: annotation
