app:
    resource: '@AppBundle/Controller/'
    type: annotation

front:
    resource: "@FrontBundle/Controller/"
    type:     annotation
    prefix:   /front

team:
    resource: "@TeamBundle/Controller/"
    type:     annotation
    prefix:   /team

joueur:
    resource: '@JoueurBundle/Controller/'
    prefix: /joueur
    type: annotation

user:
    resource: "@UserBundle/Controller/"
    type:     annotation
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
