<?php

namespace Forum\ForumBundle\Repository;

use Forum\ForumBundle\Entity\Comment;

/**
 * CommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentRepository extends \Doctrine\ORM\EntityRepository
{

    /**
     * @param $subject
     * @return int
     * @throws \Doctrine\ORM\NonUniqueResultException
     */
    public function getTotalNumberOfComment($subject): int
    {
        return $this->createQueryBuilder('s')
            ->andWhere('s.subject = :subject')
            ->setParameter('subject' , $subject)
            ->select('COUNT(s.subject)')
            ->getQuery()
            ->getSingleScalarResult();
    }

    /**
     * @param $subject
     * @return mixed
     */
    public function getCommentsBySubject($subject)
    {
        $query = $this->getEntityManager()
            ->createQuery("select m from ForumBundle:Comment m WHERE m.subject=:P")
            ->setParameter('P', $subject);
        return $query->getResult();
    }


}
