<?php

namespace Forum\ForumBundle\Repository;

/**
 * CommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentRepository extends \Doctrine\ORM\EntityRepository
{

    /**
     * @param $subject
     * @return int
     * @throws \Doctrine\ORM\NonUniqueResultException
     */
    public function getTotalNumberOfComment($subject): int
    {
        return $this->createQueryBuilder('s')
            ->andWhere('s.subject = :subject')
            ->setParameter('subject' , $subject)
            ->select('COUNT(s.subject)')
            ->getQuery()
            ->getSingleScalarResult();
    }

}
