<?php

namespace Match\MatchBundle\Repository;

/**
 * EventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventRepository extends \Doctrine\ORM\EntityRepository
{

    public function gameResult()
    {
        $query = $this->getEntityManager()
            ->createQuery("SELECT e FROM MatchBundle:Event e 
                                WHERE s.shots > -1");
        return $query->getResult();
    }
}
