<?php

namespace Match\MatchBundle\Repository;

/**
 * MatchRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MatchRepository extends \Doctrine\ORM\EntityRepository
{
    public function searchDQL($name)
    {
        $query = $this->getEntityManager()
            ->createQuery("SELECT t FROM MatchBundle:Match t 
                                WHERE t.team1 OR t.team2  LIKE :name")
            ->setParameter('name', '%' . $name . '%');
        return $query->getResult();

    }
}
