<?php

namespace Match\MatchBundle\Repository;

/**
 * PlayerTestRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlayerTestRepository extends \Doctrine\ORM\EntityRepository
{
}
