<?php

namespace Match\MatchBundle\Repository;

/**
 * StatisticsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StatisticsRepository extends \Doctrine\ORM\EntityRepository
{
    public function gameResult()
    {
        $query = $this->getEntityManager()
            ->createQuery("SELECT s FROM MatchBundle:Statistics s 
                                WHERE s.shots > -1");
        return $query->getResult();
    }

}
