<?php

namespace Match\MatchBundle\Repository;

/**
 * TeamTestRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TeamTestRepository extends \Doctrine\ORM\EntityRepository
{
}
