<?php

namespace Common\LocationBundle\Repository;

/**
 * GeoCodeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GeoCodeRepository extends \Doctrine\ORM\EntityRepository
{
}
