<?php

namespace Player\PlayerBundle\Repository;

/**
 * ClubRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClubRepository extends \Doctrine\ORM\EntityRepository
{
    public function findbyPlayer($id){
        $qb =$this->createQueryBuilder('c')
            ->where('c.player= :id')
            ->setParameter('id',$id)
            ->getQuery();

        return $qb->execute();
    }
}
