<?php

namespace Player\PlayerBundle\Repository;

/**
 * PlayerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlayerRepository extends \Doctrine\ORM\EntityRepository
{
    public function goalScoredByTeam($team){
        $query= $this->createQueryBuilder('p')
            ->where('p.nationalTeam = :team')
            ->setParameter('team',$team)
            ->select('SUM(p.goalScored)')
            ->getQuery();
        return $query->getSingleScalarResult();

    }
    public function shotsByTeam($team){
        $query= $this->createQueryBuilder('p')
            ->where('p.nationalTeam = :team')
            ->setParameter('team',$team)
            ->select('SUM(p.shots)')
            ->getQuery();
        return $query->getSingleScalarResult();
    }
    public function shotsOnTargetByTeam($team){
        $query= $this->createQueryBuilder('p')
            ->where('p.nationalTeam = :team')
            ->setParameter('team',$team)
            ->select('SUM(p.shotsOnTarget)')
            ->getQuery();
        return $query->getSingleScalarResult();
    }
    public function assistsByTeam($team){
        $query= $this->createQueryBuilder('p')
            ->where('p.nationalTeam = :team')
            ->setParameter('team',$team)
            ->select('SUM(p.assists)')
            ->getQuery();
        return $query->getSingleScalarResult();
    }
    public function passesByTeam($team){
        $query= $this->createQueryBuilder('p')
            ->where('p.nationalTeam = :team')
            ->setParameter('team',$team)
            ->select('SUM(p.passes)')
            ->getQuery();
        return $query->getSingleScalarResult();
    }
    public function foulsByTeam($team){
        $query= $this->createQueryBuilder('p')
            ->where('p.nationalTeam = :team')
            ->setParameter('team',$team)
            ->select('SUM(p.fouls)')
            ->getQuery();
        return $query->getSingleScalarResult();
    }
    public function yellowCardsByTeam($team){
        $query= $this->createQueryBuilder('p')
            ->where('p.nationalTeam = :team')
            ->setParameter('team',$team)
            ->select('SUM(p.yellowCard)')
            ->getQuery();
        return $query->getSingleScalarResult();
    }
    public function redCardsByTeam($team){
        $query= $this->createQueryBuilder('p')
            ->where('p.nationalTeam = :team')
            ->setParameter('team',$team)
            ->select('SUM(p.redCard)')
            ->getQuery();
        return $query->getSingleScalarResult();
    }
}
