<?php

namespace Player\PlayerBundle\Repository;

/**
 * ViewRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ViewRepository extends \Doctrine\ORM\EntityRepository
{
}
