<?php

namespace Reservation\TicketBundle\Repository;

/**
 * MatcheRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MatcheRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllBy($criteria)
    {

        $qb = $this->createQueryBuilder('m')
            ->andWhere('m.id in (:criteria)')
            ->setParameter('criteria', $criteria);

        return $qb->getQuery()->getResult();
    }
}
