<?php

namespace Reservation\TicketBundle\Repository;

/**
 * TicketRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TicketRepository extends \Doctrine\ORM\EntityRepository
{


    public function findAllBy($criteria)
    {

        $qb = $this->createQueryBuilder('t')
            ->select('t')
            ->where('t.match in (:criteria)')
            ->setParameter('criteria', $criteria);

        return $qb->getQuery()->getArrayResult();
    }
}
