<?php

namespace News\NewsBundle\Repository;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends \Doctrine\ORM\EntityRepository
{
    public function findSpotLight($max = 2)
    {

        return $this->createQueryBuilder('a')
            ->setMaxResults($max)
            ->getQuery()
            ->getResult();
    }


    public function findLatest($max = 1)
    {
        return $this->createQueryBuilder('a')
            ->setMaxResults($max)
            ->getQuery()
            ->getResult();
    }

    public function findRated($max)
    {
        return $this->createQueryBuilder('a')
            ->setMaxResults($max)
//            ->orderBy('a.created', )
            ->getQuery()
            ->getResult();
    }

    public function getPopularArticles($max = 3)
    {
        return $this->createQueryBuilder('a')
            ->setMaxResults($max)
            ->getQuery()
            ->getResult();
    }
}
