<?php

namespace News\NewsBundle\Repository;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends \Doctrine\ORM\EntityRepository
{
    public function findSpotLight()
    {

        return $this->createQueryBuilder('a')
            ->setMaxResults(2)
            ->getQuery()
            ->getResult();
    }


    public function findLatest()
    {
        return $this->createQueryBuilder('a')
            ->setMaxResults(1)
//            ->orderBy('a.created', )
            ->getQuery()
            ->getOneOrNullResult();
    }

    public function findRated($max)
    {
        return $this->createQueryBuilder('a')
            ->setMaxResults($max)
//            ->orderBy('a.created', )
            ->getQuery()
            ->getResult();
    }
}
