<?php

namespace News\NewsBundle\Repository;

/**
 * VoteUpRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VoteUpRepository extends \Doctrine\ORM\EntityRepository
{

    /**
     * @param $article
     * @return int
     */
    public function getTotalNumberOfVote($article): int
    {
        return $this->createQueryBuilder('a')
            ->andWhere('a.article = :article')
            ->setParameter('article', $article)
            ->select('COUNT(a.article)')
            ->getQuery()
            ->getSingleScalarResult();
    }

    public function getArticleVotedByUser($article, $user)
    {

        // Preventing ALIAS
        $query = $this->_em->createQueryBuilder()
            ->select('a.article')
            ->from('NewsBundle:VoteUp', 'a')
            ->join('NewsBundle:Article', 'b', 'with', 'a.article = b.id')
            ->andWhere('a.article = :article')
            ->andWhere('a.user = :user')
            ->setParameter('article', $article)
            ->setParameter('user', $user)
            ->getQuery();

        return array_column($query->getResult(), 1);
    }
}
