<?php

namespace Reservation\HotelBundle\Repository;

use Reservation\HotelBundle\Entity\Hotel;

/**
 * RoomRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RoomRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByHotel(Hotel $hotel)
    {
        $query = $this->createQueryBuilder('r')
            ->andWhere("r.hotel = :hotel")
            ->setParameter('hotel', $hotel)
            ->getQuery();
        return $query->getResult();
    }
}
