services:
    booking.manager:
        class: Common\BookingBundle\Manager\BookingManager
#    booking.example:
#        class: Common\BookingBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
