<?php

namespace Group\GroupBundle\Repository;

/**
 * PoolRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PoolRepository extends \Doctrine\ORM\EntityRepository
{
}
